"use server";

import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/auth/guard";
import { permKey } from "@/lib/auth/permissions";
import { audit } from "@/lib/audit";
import { calendarEventSchema, MANUALLY_CREATABLE_TYPES } from "@/lib/validation/calendar";
import type { ActionState } from "@/lib/actions/auth-actions";

// Só o formulário genérico usa esta checagem: tipos fora dessa lista
// (ENTREGA, CAPTACAO, CONTRATO) só existem porque outro módulo os gerou.
function isAutoGenerated(type: string): boolean {
  return !MANUALLY_CREATABLE_TYPES.includes(type as (typeof MANUALLY_CREATABLE_TYPES)[number]);
}

function parseEventForm(formData: FormData) {
  return calendarEventSchema.safeParse({
    title: formData.get("title"),
    type: formData.get("type") || "REUNIAO",
    startAt: formData.get("startAt"),
    endAt: formData.get("endAt"),
    allDay: formData.get("allDay") === "on",
    clientId: formData.get("clientId"),
    projectId: formData.get("projectId"),
    responsibleUserId: formData.get("responsibleUserId"),
    location: formData.get("location"),
    notes: formData.get("notes"),
  });
}

export async function createEventAction(_prev: ActionState, formData: FormData): Promise<ActionState> {
  const user = await requirePermission(permKey("CALENDAR", "CREATE"));

  const parsed = parseEventForm(formData);
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Verifique os dados informados." };
  }

  const event = await db.calendarEvent.create({ data: { organizationId: user.organizationId, ...parsed.data } });

  await audit({
    organizationId: user.organizationId,
    userId: user.id,
    action: "CALENDAR_EVENT_CREATED",
    entityType: "CalendarEvent",
    entityId: event.id,
  });

  revalidatePath("/agenda");
  return { success: "Evento criado." };
}

export async function updateEventAction(
  eventId: string,
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const user = await requirePermission(permKey("CALENDAR", "EDIT"));

  const parsed = parseEventForm(formData);
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Verifique os dados informados." };
  }

  const existing = await db.calendarEvent.findFirst({ where: { id: eventId, organizationId: user.organizationId } });
  if (!existing) return { error: "Evento não encontrado." };
  if (isAutoGenerated(existing.type)) {
    return { error: "Este evento é gerado automaticamente. Edite-o a partir do módulo de origem." };
  }

  await db.calendarEvent.update({ where: { id: eventId }, data: parsed.data });

  await audit({
    organizationId: user.organizationId,
    userId: user.id,
    action: "CALENDAR_EVENT_UPDATED",
    entityType: "CalendarEvent",
    entityId: eventId,
  });

  revalidatePath("/agenda");
  return { success: "Evento atualizado." };
}

export async function deleteEventAction(eventId: string) {
  const user = await requirePermission(permKey("CALENDAR", "DELETE"));

  const existing = await db.calendarEvent.findFirst({ where: { id: eventId, organizationId: user.organizationId } });
  if (!existing || isAutoGenerated(existing.type)) return;

  await db.calendarEvent.delete({ where: { id: eventId } });

  await audit({
    organizationId: user.organizationId,
    userId: user.id,
    action: "CALENDAR_EVENT_DELETED",
    entityType: "CalendarEvent",
    entityId: eventId,
  });

  revalidatePath("/agenda");
}
