"use client";

import { useMemo, useState } from "react";
import {
  startOfMonth,
  endOfMonth,
  startOfWeek,
  endOfWeek,
  eachDayOfInterval,
  addMonths,
  subMonths,
  isSameMonth,
  isSameDay,
  format,
} from "date-fns";
import { ptBR } from "date-fns/locale";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Plus, CalendarDays, List as ListIcon, Lock } from "lucide-react";
import { createEventAction, updateEventAction, deleteEventAction } from "@/lib/actions/calendar-actions";
import { CALENDAR_EVENT_TYPES, CALENDAR_EVENT_TYPE_LABELS, MANUALLY_CREATABLE_TYPES } from "@/lib/validation/calendar";
import { formatDateTime } from "@/lib/format";
import { cn } from "@/lib/cn";
import { Drawer } from "@/components/ui/drawer";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { EventForm, type EventFormValues } from "./event-form";

interface EventRow {
  id: string;
  title: string;
  type: string;
  startAt: string;
  endAt: string | null;
  allDay: boolean;
  clientId: string | null;
  clientName: string | null;
  projectId: string | null;
  projectName: string | null;
  responsibleUserId: string | null;
  responsibleName: string | null;
  location: string | null;
  notes: string | null;
  sourceHref: string | null;
}

const TYPE_TONE: Record<string, "neutral" | "info" | "success" | "warning" | "error" | "accent"> = {
  CAPTACAO: "accent",
  REUNIAO: "info",
  ENTREGA: "success",
  VENCIMENTO: "warning",
  COBRANCA: "warning",
  CONTRATO: "error",
  TAREFA: "neutral",
  INTERNO: "neutral",
  MIDIA: "accent",
};

function isAutoGenerated(type: string): boolean {
  return !MANUALLY_CREATABLE_TYPES.includes(type as (typeof MANUALLY_CREATABLE_TYPES)[number]);
}

function toFormValues(e: EventRow): EventFormValues {
  return {
    title: e.title,
    type: e.type,
    startAt: e.startAt,
    endAt: e.endAt,
    allDay: e.allDay,
    clientId: e.clientId,
    projectId: e.projectId,
    responsibleUserId: e.responsibleUserId,
    location: e.location,
    notes: e.notes,
  };
}

export function CalendarView({
  events,
  clients,
  projects,
  users,
  permissions,
}: {
  events: EventRow[];
  clients: { id: string; companyName: string }[];
  projects: { id: string; name: string }[];
  users: { id: string; name: string }[];
  permissions: { canCreate: boolean; canEdit: boolean; canDelete: boolean };
}) {
  const [view, setView] = useState<"mes" | "lista">("mes");
  const [month, setMonth] = useState(() => new Date());
  const [creating, setCreating] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [filters, setFilters] = useState({ clientId: "", responsibleUserId: "", type: "", projectId: "" });

  const filtered = useMemo(() => {
    return events.filter((e) => {
      if (filters.clientId && e.clientId !== filters.clientId) return false;
      if (filters.responsibleUserId && e.responsibleUserId !== filters.responsibleUserId) return false;
      if (filters.type && e.type !== filters.type) return false;
      if (filters.projectId && e.projectId !== filters.projectId) return false;
      return true;
    });
  }, [events, filters]);

  const editing = editingId ? filtered.find((e) => e.id === editingId) : null;

  const days = useMemo(() => {
    const start = startOfWeek(startOfMonth(month), { weekStartsOn: 0 });
    const end = endOfWeek(endOfMonth(month), { weekStartsOn: 0 });
    return eachDayOfInterval({ start, end });
  }, [month]);

  const eventsByDay = useMemo(() => {
    const map = new Map<string, EventRow[]>();
    for (const e of filtered) {
      const key = format(new Date(e.startAt), "yyyy-MM-dd");
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(e);
    }
    return map;
  }, [filtered]);

  const listEvents = useMemo(
    () => [...filtered].sort((a, b) => new Date(a.startAt).getTime() - new Date(b.startAt).getTime()),
    [filtered],
  );

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2">
          <select
            value={filters.clientId}
            onChange={(e) => setFilters((f) => ({ ...f, clientId: e.target.value }))}
            className="h-10 rounded-[10px] border border-border bg-card px-3 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent/40"
          >
            <option value="">Todos os clientes</option>
            {clients.map((c) => (
              <option key={c.id} value={c.id}>
                {c.companyName}
              </option>
            ))}
          </select>
          <select
            value={filters.responsibleUserId}
            onChange={(e) => setFilters((f) => ({ ...f, responsibleUserId: e.target.value }))}
            className="h-10 rounded-[10px] border border-border bg-card px-3 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent/40"
          >
            <option value="">Todos os responsáveis</option>
            {users.map((u) => (
              <option key={u.id} value={u.id}>
                {u.name}
              </option>
            ))}
          </select>
          <select
            value={filters.projectId}
            onChange={(e) => setFilters((f) => ({ ...f, projectId: e.target.value }))}
            className="h-10 rounded-[10px] border border-border bg-card px-3 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent/40"
          >
            <option value="">Todos os projetos</option>
            {projects.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name}
              </option>
            ))}
          </select>
          <select
            value={filters.type}
            onChange={(e) => setFilters((f) => ({ ...f, type: e.target.value }))}
            className="h-10 rounded-[10px] border border-border bg-card px-3 text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent/40"
          >
            <option value="">Todos os tipos</option>
            {CALENDAR_EVENT_TYPES.map((t) => (
              <option key={t} value={t}>
                {CALENDAR_EVENT_TYPE_LABELS[t]}
              </option>
            ))}
          </select>
        </div>
        {permissions.canCreate && (
          <Button onClick={() => setCreating(true)}>
            <Plus size={16} /> Novo Evento
          </Button>
        )}
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-1 rounded-[10px] border border-border bg-card p-1 w-fit">
          <button
            type="button"
            onClick={() => setView("mes")}
            className={cn("flex items-center gap-1.5 rounded-[8px] px-3 py-1.5 text-sm", view === "mes" ? "bg-card-elevated text-accent-light" : "text-text-secondary")}
          >
            <CalendarDays size={14} /> Mês
          </button>
          <button
            type="button"
            onClick={() => setView("lista")}
            className={cn("flex items-center gap-1.5 rounded-[8px] px-3 py-1.5 text-sm", view === "lista" ? "bg-card-elevated text-accent-light" : "text-text-secondary")}
          >
            <ListIcon size={14} /> Agenda
          </button>
        </div>

        {view === "mes" && (
          <div className="flex items-center gap-2">
            <button type="button" onClick={() => setMonth((m) => subMonths(m, 1))} className="rounded-[8px] p-1.5 text-text-secondary hover:bg-card">
              <ChevronLeft size={18} />
            </button>
            <span className="w-36 text-center text-sm font-medium capitalize text-text-primary">
              {format(month, "MMMM yyyy", { locale: ptBR })}
            </span>
            <button type="button" onClick={() => setMonth((m) => addMonths(m, 1))} className="rounded-[8px] p-1.5 text-text-secondary hover:bg-card">
              <ChevronRight size={18} />
            </button>
            <Button variant="outline" size="sm" onClick={() => setMonth(new Date())}>
              Hoje
            </Button>
          </div>
        )}
      </div>

      {view === "mes" ? (
        <div className="overflow-hidden rounded-2xl border border-border">
          <div className="grid grid-cols-7 border-b border-border bg-bg-secondary text-center text-xs font-medium uppercase tracking-wide text-text-tertiary">
            {["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((d) => (
              <div key={d} className="py-2">
                {d}
              </div>
            ))}
          </div>
          <div className="grid grid-cols-7">
            {days.map((day) => {
              const key = format(day, "yyyy-MM-dd");
              const dayEvents = eventsByDay.get(key) ?? [];
              const inMonth = isSameMonth(day, month);
              const today = isSameDay(day, new Date());
              return (
                <div key={key} className={cn("min-h-[110px] border-b border-r border-border p-1.5", !inMonth && "bg-bg-secondary/40")}>
                  <span className={cn("inline-flex h-6 w-6 items-center justify-center rounded-full text-xs", today ? "bg-accent text-accent-on font-semibold" : inMonth ? "text-text-secondary" : "text-text-tertiary")}>
                    {format(day, "d")}
                  </span>
                  <div className="mt-1 flex flex-col gap-1">
                    {dayEvents.slice(0, 3).map((e) => (
                      <button
                        key={e.id}
                        type="button"
                        onClick={() => setEditingId(e.id)}
                        className="truncate rounded-[6px] bg-card-elevated px-1.5 py-0.5 text-left text-[11px] text-text-secondary hover:text-text-primary"
                        title={e.title}
                      >
                        <Badge tone={TYPE_TONE[e.type] ?? "neutral"} className="mr-1 px-1 py-0 text-[10px]">
                          {CALENDAR_EVENT_TYPE_LABELS[e.type as keyof typeof CALENDAR_EVENT_TYPE_LABELS]?.slice(0, 4) ?? e.type}
                        </Badge>
                        {e.title}
                      </button>
                    ))}
                    {dayEvents.length > 3 && <span className="text-[11px] text-text-tertiary">+{dayEvents.length - 3} mais</span>}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ) : listEvents.length === 0 ? (
        <EmptyState icon={<CalendarDays size={28} />} title="Nenhum evento encontrado" description="Ajuste os filtros ou crie um novo evento." />
      ) : (
        <div className="flex flex-col divide-y divide-border rounded-2xl border border-border">
          {listEvents.map((e) => (
            <button
              key={e.id}
              type="button"
              onClick={() => setEditingId(e.id)}
              className="flex items-center justify-between gap-3 px-4 py-3 text-left hover:bg-card"
            >
              <div className="flex items-center gap-3">
                <Badge tone={TYPE_TONE[e.type] ?? "neutral"}>{CALENDAR_EVENT_TYPE_LABELS[e.type as keyof typeof CALENDAR_EVENT_TYPE_LABELS] ?? e.type}</Badge>
                <div>
                  <p className="text-sm text-text-primary">{e.title}</p>
                  <p className="text-xs text-text-tertiary">
                    {[e.clientName, e.projectName, e.location].filter(Boolean).join(" · ") || "—"}
                  </p>
                </div>
              </div>
              <span className="text-xs text-text-tertiary">{e.allDay ? format(new Date(e.startAt), "dd/MM/yyyy") : formatDateTime(new Date(e.startAt))}</span>
            </button>
          ))}
        </div>
      )}

      <Drawer open={creating} onClose={() => setCreating(false)} title="Novo Evento">
        <EventForm action={createEventAction} clients={clients} projects={projects} users={users} submitLabel="Criar evento" onSuccess={() => setCreating(false)} />
      </Drawer>

      <Drawer open={!!editing} onClose={() => setEditingId(null)} title={editing?.title ?? ""}>
        {editing &&
          (isAutoGenerated(editing.type) ? (
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2 rounded-[10px] border border-border bg-bg-secondary px-3 py-2.5 text-sm text-text-secondary">
                <Lock size={14} /> Este evento é gerado automaticamente e não pode ser editado aqui.
              </div>
              <div className="text-sm text-text-secondary">
                <p>
                  <span className="text-text-tertiary">Quando: </span>
                  {formatDateTime(new Date(editing.startAt))}
                </p>
                {editing.location && (
                  <p>
                    <span className="text-text-tertiary">Local: </span>
                    {editing.location}
                  </p>
                )}
              </div>
              {editing.sourceHref && (
                <Link href={editing.sourceHref}>
                  <Button variant="secondary">Ver origem</Button>
                </Link>
              )}
            </div>
          ) : (
            <div className="flex flex-col gap-4">
              <EventForm
                key={editing.id}
                action={updateEventAction.bind(null, editing.id)}
                defaultValues={toFormValues(editing)}
                clients={clients}
                projects={projects}
                users={users}
                submitLabel="Salvar alterações"
              />
              {permissions.canDelete && (
                <Button
                  variant="danger"
                  onClick={async () => {
                    await deleteEventAction(editing.id);
                    setEditingId(null);
                  }}
                >
                  Excluir evento
                </Button>
              )}
            </div>
          ))}
      </Drawer>
    </div>
  );
}
