import type { Billing, CardMode } from "@/lib/pricing/engine";

// Tabela do "Lumi · Guia Comercial · Preços & Comissões" (outubro/2026).
// O botão "Carregar tabela do Guia" em Serviços cria ou atualiza estes
// serviços pelo guideKey — rodar de novo nunca duplica, e serviços criados à
// mão pelo time não são tocados.
export interface GuideService {
  guideKey: string;
  category: string;
  name: string;
  tagline?: string;
  description?: string;
  features: string[];
  billing: Billing;
  price: number;
  currency?: "BRL" | "USD";
  priceIsFrom?: boolean;
  monthlyFee?: number;
  cardMode?: CardMode;
  cardPrice?: number;
  maxInstallments?: number;
  minMonths?: number;
  badge?: string;
  isAddon?: boolean;
  terms?: string;
  // Comissão do comercial (Guia, página de cada produto). Adicional sem valor
  // próprio segue a % do plano vendido junto.
  commissionPercent?: number;
  commissionFixed?: number;
  // Eventos: 50% da comissão quando o sinal entra e 50% na quitação.
  commissionSplit?: boolean;
}

const LOCOMOCAO = "Locomoção por conta do cliente.";

const COMMERCIAL_GUIDE: GuideService[] = [
  // ---------- Captação Mobile ----------
  {
    guideKey: "captacao-mobile-essencial",
    commissionPercent: 15,
    category: "Captação Mobile",
    name: "Captação Mobile · Essencial",
    tagline: "Presença constante · 5 vídeos por mês",
    features: ["5 vídeos por mês", "1 diária de captação no negócio", "Roteiro e direção", "Edição vertical para Reels/TikTok"],
    billing: "MENSAL",
    price: 1590,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-mobile-crescimento",
    commissionPercent: 20,
    category: "Captação Mobile",
    name: "Captação Mobile · Crescimento",
    tagline: "Ritmo de 2 posts por semana · 8 vídeos por mês",
    features: ["8 vídeos por mês", "Tudo do Essencial", "Planejamento de pautas do mês", "Capas e legendas na tela"],
    billing: "MENSAL",
    price: 2290,
    minMonths: 3,
    badge: "Mais vendido",
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-mobile-premium",
    commissionPercent: 30,
    category: "Captação Mobile",
    name: "Captação Mobile · Premium",
    tagline: "Dominar o feed · 12 vídeos por mês",
    features: ["12 vídeos por mês", "Tudo do Crescimento", "Copy + tags planejadas inclusas", "Prioridade de agenda e entrega"],
    billing: "MENSAL",
    price: 3190,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  // ---------- Captação Câmera ----------
  {
    guideKey: "captacao-camera-essencial",
    commissionPercent: 15,
    category: "Captação Câmera",
    name: "Captação Câmera · Essencial",
    tagline: "Imagem que posiciona · 5 vídeos por mês",
    features: ["5 vídeos por mês", "Câmera profissional, lentes e luz", "Roteiro e direção", "Edição e colorização"],
    billing: "MENSAL",
    price: 2490,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-camera-crescimento",
    commissionPercent: 20,
    category: "Captação Câmera",
    name: "Captação Câmera · Crescimento",
    tagline: "Marca forte e consistente · 8 vídeos por mês",
    features: ["8 vídeos por mês", "Tudo do Essencial", "Planejamento de pautas do mês", "Motion simples (vinheta, letterings)"],
    billing: "MENSAL",
    price: 3590,
    minMonths: 3,
    badge: "Mais vendido",
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-camera-premium",
    commissionPercent: 30,
    category: "Captação Câmera",
    name: "Captação Câmera · Premium",
    tagline: "Produção de marca grande · 12 vídeos por mês",
    features: ["12 vídeos por mês", "Tudo do Crescimento", "Copy + tags planejadas inclusas", "Direção de fotografia e áudio dedicado"],
    billing: "MENSAL",
    price: 4990,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  // ---------- Adicionais da captação ----------
  {
    guideKey: "adicional-copy-essencial",
    category: "Adicionais da captação",
    name: "Copy + tags planejadas (plano Essencial)",
    features: ["Descrição estratégica de cada post", "Hashtags e tags pensadas para alcance"],
    billing: "MENSAL",
    price: 200,
    isAddon: true,
  },
  {
    guideKey: "adicional-copy-crescimento",
    category: "Adicionais da captação",
    name: "Copy + tags planejadas (plano Crescimento)",
    features: ["Descrição estratégica de cada post", "Hashtags e tags pensadas para alcance"],
    billing: "MENSAL",
    price: 280,
    isAddon: true,
  },
  {
    guideKey: "adicional-video-extra-mobile",
    category: "Adicionais da captação",
    name: "Vídeo extra · Mobile",
    tagline: "Por vídeo",
    features: ["Vídeo adicional captado na mesma diária"],
    billing: "PONTUAL",
    price: 250,
    isAddon: true,
  },
  {
    guideKey: "adicional-video-extra-camera",
    category: "Adicionais da captação",
    name: "Vídeo extra · Câmera",
    tagline: "Por vídeo",
    features: ["Vídeo adicional captado na mesma diária"],
    billing: "PONTUAL",
    price: 400,
    isAddon: true,
  },
  {
    guideKey: "adicional-fotos-mobile",
    category: "Adicionais da captação",
    name: "Pacote de fotos · Mobile",
    features: ["15 fotos tratadas feitas na mesma diária"],
    billing: "PONTUAL",
    price: 350,
    isAddon: true,
  },
  {
    guideKey: "adicional-fotos-camera",
    category: "Adicionais da captação",
    name: "Pacote de fotos · Câmera",
    features: ["15 fotos tratadas feitas na mesma diária"],
    billing: "PONTUAL",
    price: 550,
    isAddon: true,
  },
  {
    guideKey: "adicional-agendamento-postagem",
    category: "Adicionais da captação",
    name: "Agendamento e postagem",
    features: ["A Lumi publica os vídeos nas redes do cliente"],
    billing: "MENSAL",
    price: 300,
    isAddon: true,
  },
  // ---------- Produções sob projeto ----------
  {
    guideKey: "producao-mobile",
    commissionPercent: 15,
    category: "Produções sob projeto",
    name: "Produção Mobile",
    tagline: "Conteúdo ágil, produção inteligente",
    features: ["Roteiro e direção", "Captação mobile", "Edição para redes, formatos verticais"],
    billing: "PONTUAL",
    price: 1200,
    priceIsFrom: true,
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-producao",
    commissionPercent: 20,
    category: "Produções sob projeto",
    name: "Produção",
    tagline: "Mais controle, mais possibilidades",
    features: ["Estratégia, roteiro e direção criativa", "Equipe, câmera e direção de fotografia", "Edição, colorização e motion"],
    billing: "PONTUAL",
    price: 3500,
    priceIsFrom: true,
    badge: "Mais escolhido",
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-cinema",
    commissionPercent: 30,
    category: "Produções sob projeto",
    name: "Produção Cinema",
    tagline: "Campanhas e brand films",
    features: ["Estrutura e equipe cinematográfica", "Drone e pós-produção avançada", "Acompanhamento completo"],
    billing: "PONTUAL",
    price: 8000,
    priceIsFrom: true,
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-cobertura-evento",
    commissionPercent: 15,
    category: "Produções sob projeto",
    name: "Cobertura de evento",
    tagline: "Até 4 horas, com câmera",
    features: ["Cobertura de até 4 horas", "Captação com câmera profissional", "Edição do material"],
    billing: "PONTUAL",
    price: 1800,
    priceIsFrom: true,
    terms: LOCOMOCAO,
  },
  {
    guideKey: "producao-drone",
    category: "Produções sob projeto",
    name: "Drone",
    tagline: "Adicional por diária",
    features: ["Imagens aéreas com drone na diária de captação"],
    billing: "PONTUAL",
    price: 600,
    priceIsFrom: true,
    isAddon: true,
  },
  {
    guideKey: "producao-logo-animada",
    commissionPercent: 15,
    category: "Produções sob projeto",
    name: "Logo animada / vinheta",
    features: ["Animação da marca para abertura e encerramento de vídeos"],
    billing: "PONTUAL",
    price: 800,
    priceIsFrom: true,
  },
  // ---------- Sites ----------
  {
    guideKey: "site-essencial",
    commissionFixed: 500,
    category: "Sites",
    name: "Site Essencial",
    tagline: "Presença profissional + WhatsApp",
    features: ["Site completo e responsivo", "Botão direto para o WhatsApp", "Mensalidade cobre hospedagem e manutenção"],
    billing: "PONTUAL",
    price: 1500,
    monthlyFee: 100,
    cardMode: "FIXED",
    cardPrice: 1800,
    maxInstallments: 5,
    terms: "R$ 1.500 à vista ou R$ 1.800 em até 5x sem juros, mais R$ 100/mês de hospedagem e manutenção.",
  },
  {
    guideKey: "site-formulario",
    commissionFixed: 100,
    category: "Sites",
    name: "Formulário Inteligente",
    tagline: "CRM antes do WhatsApp",
    features: ["Lead preenche nome, interesse e urgência", "Chega organizado para o atendente", "Menos lead frio, mais conversão"],
    billing: "PONTUAL",
    price: 500,
    badge: "Upsell",
    isAddon: true,
  },
  {
    guideKey: "site-cardapio-delivery",
    commissionFixed: 500,
    category: "Sites",
    name: "Site Cardápio Delivery",
    tagline: "Modelo pronto para delivery",
    features: ["Cardápio com fotos, busca e carrinho", "Pedido fechado direto no WhatsApp", "CRM automatizado: pedido chega organizado"],
    billing: "PONTUAL",
    price: 1500,
    monthlyFee: 100,
    cardMode: "FIXED",
    cardPrice: 1800,
    maxInstallments: 5,
    terms: "R$ 1.500 à vista ou R$ 1.800 em até 5x sem juros, mais R$ 100/mês de hospedagem e manutenção.",
  },
  {
    guideKey: "site-internacional-premium",
    commissionFixed: 1000,
    category: "Sites",
    name: "Site Internacional Premium",
    tagline: "Para negócios fora do Brasil",
    features: ["Site premium, bem produzido", "Hospedagem e manutenção por US$ 20/mês", "Recebimento em dólar ou euro"],
    billing: "PONTUAL",
    price: 750,
    currency: "USD",
    monthlyFee: 20,
    cardMode: "NONE",
    terms: "50% de entrada para iniciar o projeto e 50% na entrega.",
  },
  // ---------- Cutlist ----------
  {
    guideKey: "cutlist-simples",
    commissionFixed: 80,
    category: "Cutlist",
    name: "Cutlist · Simples",
    tagline: "Sistema de agendamento",
    features: ["Agendamento automático online", "Espelhamento no Google Agenda", "\"Meu Link\": página de links para todas as redes"],
    billing: "MENSAL",
    price: 150,
  },
  {
    guideKey: "cutlist-pro",
    commissionFixed: 100,
    category: "Cutlist",
    name: "Cutlist · Pro",
    tagline: "Sistema de agendamento",
    features: ["Tudo do Simples", "Recursos avançados de agenda", "Ideal para equipes com vários profissionais"],
    billing: "MENSAL",
    price: 190,
    badge: "Recomendado",
  },
  // ---------- Consultoria ----------
  {
    guideKey: "consultoria-perfil-ia",
    commissionPercent: 15,
    category: "Consultoria",
    name: "Consultoria de Perfil com IA",
    tagline: "Posicionamento para quem está começando",
    features: [
      "Análise completa do perfil feita com inteligência artificial",
      "Diagnóstico de posicionamento: quem você é, para quem fala, o que vende",
      "Manual de posicionamento para seguir no dia a dia",
    ],
    billing: "PONTUAL",
    price: 997,
  },
  // ---------- UGC ----------
  {
    guideKey: "ugc-portfolio-casting",
    commissionFixed: 100,
    category: "UGC",
    name: "Portfólio UGC + Casting",
    tagline: "Agenciado Lumi para sempre",
    features: [
      "Portfólio UGC profissional",
      "Ensaio de fotos ultrarrealistas geradas com IA",
      "Casting e entrada no banco de talentos Lumi",
      "Agenciamento vitalício: a Lumi envia o perfil para marcas e traz propostas",
    ],
    billing: "PONTUAL",
    price: 500,
    cardMode: "FIXED",
    cardPrice: 600,
    maxInstallments: 5,
    terms: "O valor paga a preparação do perfil; trabalhos com marcas não são garantidos.",
  },
  // ---------- Figuras Públicas ----------
  {
    guideKey: "figuras-publicas-tabela",
    commissionPercent: 15,
    category: "Figuras Públicas",
    name: "Conteúdo para Figuras Públicas",
    tagline: "Qualidade, não quantidade",
    features: ["Edição e produção personalizada", "YouTube, Instagram, TikTok e Facebook", "Postagem e gestão do conteúdo"],
    billing: "MENSAL",
    price: 3500,
    cardMode: "NONE",
    terms: "Pagamento mensal à vista, sem parcelamento.",
  },
  {
    guideKey: "figuras-publicas-oferta-decisao",
    commissionPercent: 15,
    category: "Figuras Públicas",
    name: "Figuras Públicas · Fechamento no ato",
    tagline: "Condição válida apenas no momento da negociação",
    features: ["Mesma entrega da tabela", "R$ 500 de desconto pelo pagamento à vista no ato"],
    billing: "MENSAL",
    price: 3000,
    cardMode: "NONE",
    terms: "Condição especial válida somente no momento da negociação. Pagamento à vista.",
  },
  {
    guideKey: "figuras-publicas-parceria",
    commissionPercent: 15,
    category: "Figuras Públicas",
    name: "Parceria Lumi · Figuras Públicas",
    tagline: "Contrato de 6 meses",
    features: [
      "Mesma entrega da tabela",
      "Mensalidade de R$ 3.000",
      "Participação de 40% na receita gerada pelos conteúdos produzidos pela Lumi",
    ],
    billing: "MENSAL",
    price: 3000,
    cardMode: "NONE",
    minMonths: 6,
    badge: "Parceria",
    terms: "A participação de 40% vale somente para a receita originada dos conteúdos produzidos pela Lumi, conforme definido em contrato.",
  },
  // ---------- Gestão Completa ----------
  {
    guideKey: "gestao-completa",
    commissionPercent: 15,
    category: "Gestão Completa",
    name: "Gestão Completa",
    tagline: "Social media, tráfego e audiovisual",
    features: [
      "Social media: planejamento, calendário, copy e postagem",
      "Audiovisual: captação mensal com câmera",
      "Tráfego pago: criação e gestão de campanhas",
      "Relatório mensal de métricas e resultados",
    ],
    billing: "MENSAL",
    price: 5900,
    priceIsFrom: true,
    minMonths: 6,
    terms: "Verba de anúncios paga à parte pelo cliente. Escopo e valor final definidos após diagnóstico.",
  },
];

// ---------------------------------------------------------------------------
// Plano de Tráfego Pago (outubro/2026). Comissão só sobre o serviço, nunca
// sobre a verba de anúncio — a verba o cliente paga direto ao Meta/Google.
// ---------------------------------------------------------------------------
const VERBA = "Investimento em anúncios (verba) pago pelo cliente direto às plataformas, à parte deste valor.";

const TRAFFIC: GuideService[] = [
  {
    guideKey: "trf-start",
    category: "Tráfego Pago",
    name: "Tráfego Start",
    tagline: "Primeiros anúncios · investimento recomendado de R$ 600 a R$ 1.500/mês",
    features: ["1 objetivo · Meta (Instagram e Facebook)", "Até 2 campanhas ativas", "3 artes estáticas por mês", "Relatório mensal simples"],
    billing: "MENSAL",
    price: 990,
    minMonths: 3,
    commissionPercent: 15,
    terms: `${VERBA} Contrato mínimo de 3 meses.`,
  },
  {
    guideKey: "trf-cresc",
    category: "Tráfego Pago",
    name: "Tráfego Crescimento",
    tagline: "Mais contatos, mais canais · investimento recomendado de R$ 1.500 a R$ 5.000/mês",
    features: ["Até 2 objetivos · Meta + Google Pesquisa", "Até 4 campanhas + remarketing", "6 artes por mês", "Relatório quinzenal + reunião mensal"],
    billing: "MENSAL",
    price: 1790,
    minMonths: 3,
    badge: "Mais vendido",
    commissionPercent: 20,
    terms: `${VERBA} Contrato mínimo de 3 meses.`,
  },
  {
    guideKey: "trf-perf",
    category: "Tráfego Pago",
    name: "Tráfego Performance",
    tagline: "Escala com medição de vendas · investimento recomendado de R$ 5.000 a R$ 15.000/mês",
    features: ["Objetivos e campanhas sem limite", "Meta + Google + TikTok", "10 artes + 2 vídeos curtos editados", "Pixel e API de conversões · relatório semanal"],
    billing: "MENSAL",
    price: 2990,
    minMonths: 3,
    commissionPercent: 25,
    terms: `${VERBA} Contrato mínimo de 3 meses.`,
  },
  {
    guideKey: "trf-escala",
    category: "Tráfego Pago",
    name: "Tráfego Escala",
    tagline: "Para investimento acima de R$ 15.000/mês · 15% da verba",
    features: ["Tudo do Performance", "Serviço de 15% da verba mensal (mínimo R$ 2.990)", "Escopo definido com a diretoria"],
    billing: "MENSAL",
    price: 2990,
    priceIsFrom: true,
    minMonths: 3,
    commissionPercent: 20,
    terms: `${VERBA} Contrato mínimo de 3 meses.`,
  },
  {
    guideKey: "trf-impl",
    category: "Tráfego Pago",
    name: "Taxa de implantação do tráfego",
    tagline: "Pagamento único",
    features: ["Configuração da conta de anúncios", "Pixel e públicos", "Primeiras campanhas"],
    billing: "PONTUAL",
    price: 490,
    isAddon: true,
    terms: "Isenta para contrato de 6 meses ou para clientes de Captação ou Site — nesses casos, não inclua no orçamento.",
  },
  {
    guideKey: "trf-lp",
    category: "Tráfego Pago",
    name: "Landing page de campanha",
    features: ["Página de destino para a campanha"],
    billing: "PONTUAL",
    price: 900,
    isAddon: true,
    commissionPercent: 10,
  },
  {
    guideKey: "trf-vid",
    category: "Tráfego Pago",
    name: "Vídeo extra para anúncio",
    features: ["Vídeo adicional editado para anúncio"],
    billing: "PONTUAL",
    price: 250,
    isAddon: true,
    commissionPercent: 10,
  },
];

// ---------------------------------------------------------------------------
// Eventos & Ensaios (outubro/2026). Eventos: sinal de 50% para reservar a
// data, restante até 7 dias antes, parcelamento em até 3x. Ensaios: à vista.
// ---------------------------------------------------------------------------
const EVENT_TERMS =
  "Sinal de 50% para reservar a data; restante até 7 dias antes do evento. Cancelamento: o sinal não é devolvido e a data pode ser remarcada uma vez. Locomoção, estacionamento e taxas do local por conta do cliente.";
const SHOOT_TERMS = "Pagamento à vista. Locomoção e taxas de local por conta do cliente.";

function hourly(
  key: string,
  category: string,
  label: string,
  tagline: string,
  features: string[],
  prices: [number, number, number],
  extraHour: number,
  badge?: string,
): GuideService[] {
  const packs: GuideService[] = prices.map((price, i) => ({
    guideKey: `${key}-${i + 3}h`,
    category,
    name: `${label} · ${i + 3} horas`,
    tagline,
    features: [`Cobertura de ${i + 3} horas`, ...features],
    billing: "PONTUAL",
    price,
    maxInstallments: 3,
    commissionPercent: 10,
    commissionSplit: true,
    badge: i === 0 ? badge : undefined,
    terms: EVENT_TERMS,
  }));
  packs.push({
    guideKey: `${key}-hora-extra`,
    category,
    name: `Hora extra · ${label}`,
    tagline: "Contratada antes do evento",
    features: ["1 hora além do pacote"],
    billing: "PONTUAL",
    price: extraHour,
    isAddon: true,
    maxInstallments: 3,
    commissionPercent: 10,
    commissionSplit: true,
    terms: "Hora extra pedida no dia do evento é cobrada à parte e não gera comissão.",
  });
  return packs;
}

const EVENTS: GuideService[] = [
  ...hourly("evt-foto-cel", "Eventos · Fotografia", "Fotografia celular", "Rápida, leve e acessível", ["Mínimo de 20 fotos tratadas por hora", "Galeria online em até 15 dias"], [450, 560, 670], 130),
  ...hourly("evt-foto-cam", "Eventos · Fotografia", "Fotografia câmera", "Qualidade de câmera", ["Mínimo de 30 fotos tratadas por hora", "Câmera e lentes profissionais", "Galeria online em até 15 dias"], [750, 950, 1150], 220, "Mais escolhido"),
  ...hourly("evt-vid-mob", "Eventos · Vídeo", "Vídeo mobile", "Pronto para as redes", ["1 reels resumo (até 60s) + 2 cortes verticais", "Reels em até 7 dias"], [600, 760, 920], 170),
  ...hourly("evt-vid-cam", "Eventos · Vídeo", "Vídeo câmera", "Filme do evento", ["Filme resumo de 3 a 5 min + 1 reels (60s)", "Reels em até 7 dias, filme em até 30 dias"], [1100, 1400, 1700], 320, "Mais escolhido"),
  ...hourly("evt-combo-mob", "Eventos · Combos", "Combo Mobile", "Foto celular + vídeo mobile · dois profissionais", ["Fotografia celular + vídeo mobile", "Reels resumo + cortes verticais", "Galeria online"], [950, 1190, 1430], 270),
  ...hourly("evt-combo-mix", "Eventos · Combos", "Combo Misto", "Foto câmera + vídeo mobile · dois profissionais", ["Fotografia câmera + vídeo mobile", "Reels resumo + cortes verticais", "Galeria online"], [1250, 1570, 1890], 350),
  ...hourly("evt-combo-cam", "Eventos · Combos", "Combo Câmera", "Foto câmera + vídeo câmera · dois profissionais", ["Fotografia câmera + vídeo câmera", "Filme resumo + reels", "Galeria online"], [1690, 2150, 2590], 490),
  {
    guideKey: "cas-ess",
    category: "Casamento",
    name: "Casamento Essencial",
    tagline: "Fotografia do grande dia",
    features: ["Fotografia câmera · até 6 horas", "Cerimônia e recepção", "Mínimo de 250 fotos tratadas", "Galeria online em até 30 dias"],
    billing: "PONTUAL",
    price: 2490,
    maxInstallments: 3,
    commissionFixed: 250,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  {
    guideKey: "cas-comp",
    category: "Casamento",
    name: "Casamento Completo",
    tagline: "Foto + filme",
    features: ["Fotografia + vídeo câmera · até 8 horas", "Making of, cerimônia e festa", "Mínimo de 400 fotos tratadas", "Filme de 8 a 12 min + trailer de 3 min + reels"],
    billing: "PONTUAL",
    price: 5490,
    maxInstallments: 3,
    badge: "Mais vendido",
    commissionFixed: 500,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  {
    guideKey: "cas-prem",
    category: "Casamento",
    name: "Casamento Premium",
    tagline: "A experiência completa",
    features: ["2 fotógrafos + vídeo câmera · até 10 horas", "Tudo do Completo + pré-wedding incluso", "Drone (quando permitido no local)", "Reels entregue em até 7 dias"],
    billing: "PONTUAL",
    price: 8990,
    maxInstallments: 3,
    commissionFixed: 900,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  {
    guideKey: "cas-prew",
    category: "Casamento",
    name: "Pré-wedding",
    tagline: "Ensaio do casal",
    features: ["Ensaio câmera de 2 horas", "30 fotos tratadas", "Vídeo save the date de 60s"],
    billing: "PONTUAL",
    price: 1190,
    maxInstallments: 3,
    commissionFixed: 100,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  {
    guideKey: "pkg-15anos",
    category: "Ocasiões",
    name: "Pacote 15 anos",
    tagline: "A festa + um ensaio antes",
    features: ["Combo Câmera 5h", "Ensaio câmera da debutante com 20 fotos", "Cobertura completa da festa", "Filme resumo + reels + galeria"],
    billing: "PONTUAL",
    price: 2890,
    maxInstallments: 3,
    commissionPercent: 10,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  {
    guideKey: "pkg-cha-revelacao",
    category: "Ocasiões",
    name: "Chá revelação",
    tagline: "O momento da surpresa",
    features: ["Combo Mobile 3h", "Foto celular + vídeo mobile", "Reels do momento da revelação"],
    billing: "PONTUAL",
    price: 950,
    maxInstallments: 3,
    commissionPercent: 10,
    commissionSplit: true,
    terms: EVENT_TERMS,
  },
  ...[
    { k: "ens-cel-10", n: "Ensaio celular · 10 fotos", d: "Até 40 min", p: 150, c: 20 },
    { k: "ens-cel-20", n: "Ensaio celular · 20 fotos", d: "Até 1h", p: 270, c: 30 },
    { k: "ens-cel-30", n: "Ensaio celular · 30 fotos", d: "Até 1h30", p: 370, c: 40 },
    { k: "ens-cam-10", n: "Ensaio câmera · 10 fotos", d: "Até 1h", p: 290, c: 40 },
    { k: "ens-cam-20", n: "Ensaio câmera · 20 fotos", d: "Até 1h30", p: 490, c: 60 },
    { k: "ens-cam-30", n: "Ensaio câmera · 30 fotos", d: "Até 2h", p: 690, c: 80 },
  ].map(
    (e): GuideService => ({
      guideKey: e.k,
      category: "Ensaios",
      name: e.n,
      tagline: e.k.includes("cel") ? "Ideal para redes sociais e presentes" : "Para quem quer qualidade de quadro",
      features: [`${e.d} de ensaio`, "Interno ou externo", "Fotos tratadas"],
      billing: "PONTUAL",
      price: e.p,
      maxInstallments: 1,
      commissionFixed: e.c,
      badge: e.k.endsWith("-20") ? "Mais escolhido" : undefined,
      terms: SHOOT_TERMS,
    }),
  ),
  {
    guideKey: "ens-foto-adicional-cel",
    category: "Ensaios",
    name: "Foto adicional · ensaio celular",
    features: ["Oferecida na entrega, quando o cliente vê a seleção"],
    billing: "PONTUAL",
    price: 15,
    isAddon: true,
    maxInstallments: 1,
    terms: "Fotos adicionais não geram comissão.",
  },
  {
    guideKey: "ens-foto-adicional-cam",
    category: "Ensaios",
    name: "Foto adicional · ensaio câmera",
    features: ["Oferecida na entrega, quando o cliente vê a seleção"],
    billing: "PONTUAL",
    price: 25,
    isAddon: true,
    maxInstallments: 1,
    terms: "Fotos adicionais não geram comissão.",
  },
  ...[
    { k: "add-drone", n: "Drone no evento", f: "Imagens aéreas (quando permitido no local)", p: 600 },
    { k: "add-reels-dia", n: "Reels editado no mesmo dia", f: "Reels entregue no dia do evento", p: 350 },
    { k: "add-expressa", n: "Entrega expressa das fotos", f: "Fotos entregues em até 72h", p: 250 },
    { k: "add-2foto", n: "Segundo fotógrafo câmera (3h)", f: "Mais um fotógrafo com câmera por 3 horas", p: 600 },
  ].map(
    (a): GuideService => ({
      guideKey: a.k,
      category: "Adicionais de eventos",
      name: a.n,
      features: [a.f],
      billing: "PONTUAL",
      price: a.p,
      isAddon: true,
      maxInstallments: 3,
      commissionPercent: 10,
      commissionSplit: true,
      terms: EVENT_TERMS,
    }),
  ),
];

export const GUIDE_CATALOG: GuideService[] = [...COMMERCIAL_GUIDE, ...TRAFFIC, ...EVENTS];
