import type { Billing, CardMode } from "@/lib/pricing/engine";

// Tabela do "Lumi · Guia Comercial · Preços & Comissões" (outubro/2026).
// O botão "Carregar tabela do Guia" em Serviços cria ou atualiza estes
// serviços pelo guideKey — rodar de novo nunca duplica, e serviços criados à
// mão pelo time não são tocados.
export interface GuideService {
  guideKey: string;
  category: string;
  name: string;
  tagline?: string;
  description?: string;
  features: string[];
  billing: Billing;
  price: number;
  currency?: "BRL" | "USD";
  priceIsFrom?: boolean;
  monthlyFee?: number;
  cardMode?: CardMode;
  cardPrice?: number;
  maxInstallments?: number;
  minMonths?: number;
  badge?: string;
  isAddon?: boolean;
  terms?: string;
}

const LOCOMOCAO = "Locomoção por conta do cliente.";

export const GUIDE_CATALOG: GuideService[] = [
  // ---------- Captação Mobile ----------
  {
    guideKey: "captacao-mobile-essencial",
    category: "Captação Mobile",
    name: "Captação Mobile · Essencial",
    tagline: "Presença constante · 5 vídeos por mês",
    features: ["5 vídeos por mês", "1 diária de captação no negócio", "Roteiro e direção", "Edição vertical para Reels/TikTok"],
    billing: "MENSAL",
    price: 1590,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-mobile-crescimento",
    category: "Captação Mobile",
    name: "Captação Mobile · Crescimento",
    tagline: "Ritmo de 2 posts por semana · 8 vídeos por mês",
    features: ["8 vídeos por mês", "Tudo do Essencial", "Planejamento de pautas do mês", "Capas e legendas na tela"],
    billing: "MENSAL",
    price: 2290,
    minMonths: 3,
    badge: "Mais vendido",
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-mobile-premium",
    category: "Captação Mobile",
    name: "Captação Mobile · Premium",
    tagline: "Dominar o feed · 12 vídeos por mês",
    features: ["12 vídeos por mês", "Tudo do Crescimento", "Copy + tags planejadas inclusas", "Prioridade de agenda e entrega"],
    billing: "MENSAL",
    price: 3190,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  // ---------- Captação Câmera ----------
  {
    guideKey: "captacao-camera-essencial",
    category: "Captação Câmera",
    name: "Captação Câmera · Essencial",
    tagline: "Imagem que posiciona · 5 vídeos por mês",
    features: ["5 vídeos por mês", "Câmera profissional, lentes e luz", "Roteiro e direção", "Edição e colorização"],
    billing: "MENSAL",
    price: 2490,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-camera-crescimento",
    category: "Captação Câmera",
    name: "Captação Câmera · Crescimento",
    tagline: "Marca forte e consistente · 8 vídeos por mês",
    features: ["8 vídeos por mês", "Tudo do Essencial", "Planejamento de pautas do mês", "Motion simples (vinheta, letterings)"],
    billing: "MENSAL",
    price: 3590,
    minMonths: 3,
    badge: "Mais vendido",
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  {
    guideKey: "captacao-camera-premium",
    category: "Captação Câmera",
    name: "Captação Câmera · Premium",
    tagline: "Produção de marca grande · 12 vídeos por mês",
    features: ["12 vídeos por mês", "Tudo do Crescimento", "Copy + tags planejadas inclusas", "Direção de fotografia e áudio dedicado"],
    billing: "MENSAL",
    price: 4990,
    minMonths: 3,
    terms: `1 diária de captação por mês. ${LOCOMOCAO}`,
  },
  // ---------- Adicionais da captação ----------
  {
    guideKey: "adicional-copy-essencial",
    category: "Adicionais da captação",
    name: "Copy + tags planejadas (plano Essencial)",
    features: ["Descrição estratégica de cada post", "Hashtags e tags pensadas para alcance"],
    billing: "MENSAL",
    price: 200,
    isAddon: true,
  },
  {
    guideKey: "adicional-copy-crescimento",
    category: "Adicionais da captação",
    name: "Copy + tags planejadas (plano Crescimento)",
    features: ["Descrição estratégica de cada post", "Hashtags e tags pensadas para alcance"],
    billing: "MENSAL",
    price: 280,
    isAddon: true,
  },
  {
    guideKey: "adicional-video-extra-mobile",
    category: "Adicionais da captação",
    name: "Vídeo extra · Mobile",
    tagline: "Por vídeo",
    features: ["Vídeo adicional captado na mesma diária"],
    billing: "PONTUAL",
    price: 250,
    isAddon: true,
  },
  {
    guideKey: "adicional-video-extra-camera",
    category: "Adicionais da captação",
    name: "Vídeo extra · Câmera",
    tagline: "Por vídeo",
    features: ["Vídeo adicional captado na mesma diária"],
    billing: "PONTUAL",
    price: 400,
    isAddon: true,
  },
  {
    guideKey: "adicional-fotos-mobile",
    category: "Adicionais da captação",
    name: "Pacote de fotos · Mobile",
    features: ["15 fotos tratadas feitas na mesma diária"],
    billing: "PONTUAL",
    price: 350,
    isAddon: true,
  },
  {
    guideKey: "adicional-fotos-camera",
    category: "Adicionais da captação",
    name: "Pacote de fotos · Câmera",
    features: ["15 fotos tratadas feitas na mesma diária"],
    billing: "PONTUAL",
    price: 550,
    isAddon: true,
  },
  {
    guideKey: "adicional-agendamento-postagem",
    category: "Adicionais da captação",
    name: "Agendamento e postagem",
    features: ["A Lumi publica os vídeos nas redes do cliente"],
    billing: "MENSAL",
    price: 300,
    isAddon: true,
  },
  // ---------- Produções sob projeto ----------
  {
    guideKey: "producao-mobile",
    category: "Produções sob projeto",
    name: "Produção Mobile",
    tagline: "Conteúdo ágil, produção inteligente",
    features: ["Roteiro e direção", "Captação mobile", "Edição para redes, formatos verticais"],
    billing: "PONTUAL",
    price: 1200,
    priceIsFrom: true,
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-producao",
    category: "Produções sob projeto",
    name: "Produção",
    tagline: "Mais controle, mais possibilidades",
    features: ["Estratégia, roteiro e direção criativa", "Equipe, câmera e direção de fotografia", "Edição, colorização e motion"],
    billing: "PONTUAL",
    price: 3500,
    priceIsFrom: true,
    badge: "Mais escolhido",
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-cinema",
    category: "Produções sob projeto",
    name: "Produção Cinema",
    tagline: "Campanhas e brand films",
    features: ["Estrutura e equipe cinematográfica", "Drone e pós-produção avançada", "Acompanhamento completo"],
    billing: "PONTUAL",
    price: 8000,
    priceIsFrom: true,
    terms: `${LOCOMOCAO} Valor final fechado a partir do briefing.`,
  },
  {
    guideKey: "producao-cobertura-evento",
    category: "Produções sob projeto",
    name: "Cobertura de evento",
    tagline: "Até 4 horas, com câmera",
    features: ["Cobertura de até 4 horas", "Captação com câmera profissional", "Edição do material"],
    billing: "PONTUAL",
    price: 1800,
    priceIsFrom: true,
    terms: LOCOMOCAO,
  },
  {
    guideKey: "producao-drone",
    category: "Produções sob projeto",
    name: "Drone",
    tagline: "Adicional por diária",
    features: ["Imagens aéreas com drone na diária de captação"],
    billing: "PONTUAL",
    price: 600,
    priceIsFrom: true,
    isAddon: true,
  },
  {
    guideKey: "producao-logo-animada",
    category: "Produções sob projeto",
    name: "Logo animada / vinheta",
    features: ["Animação da marca para abertura e encerramento de vídeos"],
    billing: "PONTUAL",
    price: 800,
    priceIsFrom: true,
  },
  // ---------- Sites ----------
  {
    guideKey: "site-essencial",
    category: "Sites",
    name: "Site Essencial",
    tagline: "Presença profissional + WhatsApp",
    features: ["Site completo e responsivo", "Botão direto para o WhatsApp", "Mensalidade cobre hospedagem e manutenção"],
    billing: "PONTUAL",
    price: 1500,
    monthlyFee: 100,
    cardMode: "FIXED",
    cardPrice: 1800,
    maxInstallments: 5,
    terms: "R$ 1.500 à vista ou R$ 1.800 em até 5x sem juros, mais R$ 100/mês de hospedagem e manutenção.",
  },
  {
    guideKey: "site-formulario",
    category: "Sites",
    name: "Formulário Inteligente",
    tagline: "CRM antes do WhatsApp",
    features: ["Lead preenche nome, interesse e urgência", "Chega organizado para o atendente", "Menos lead frio, mais conversão"],
    billing: "PONTUAL",
    price: 500,
    badge: "Upsell",
    isAddon: true,
  },
  {
    guideKey: "site-cardapio-delivery",
    category: "Sites",
    name: "Site Cardápio Delivery",
    tagline: "Modelo pronto para delivery",
    features: ["Cardápio com fotos, busca e carrinho", "Pedido fechado direto no WhatsApp", "CRM automatizado: pedido chega organizado"],
    billing: "PONTUAL",
    price: 1500,
    monthlyFee: 100,
    cardMode: "FIXED",
    cardPrice: 1800,
    maxInstallments: 5,
    terms: "R$ 1.500 à vista ou R$ 1.800 em até 5x sem juros, mais R$ 100/mês de hospedagem e manutenção.",
  },
  {
    guideKey: "site-internacional-premium",
    category: "Sites",
    name: "Site Internacional Premium",
    tagline: "Para negócios fora do Brasil",
    features: ["Site premium, bem produzido", "Hospedagem e manutenção por US$ 20/mês", "Recebimento em dólar ou euro"],
    billing: "PONTUAL",
    price: 750,
    currency: "USD",
    monthlyFee: 20,
    cardMode: "NONE",
    terms: "50% de entrada para iniciar o projeto e 50% na entrega.",
  },
  // ---------- Cutlist ----------
  {
    guideKey: "cutlist-simples",
    category: "Cutlist",
    name: "Cutlist · Simples",
    tagline: "Sistema de agendamento",
    features: ["Agendamento automático online", "Espelhamento no Google Agenda", "\"Meu Link\": página de links para todas as redes"],
    billing: "MENSAL",
    price: 150,
  },
  {
    guideKey: "cutlist-pro",
    category: "Cutlist",
    name: "Cutlist · Pro",
    tagline: "Sistema de agendamento",
    features: ["Tudo do Simples", "Recursos avançados de agenda", "Ideal para equipes com vários profissionais"],
    billing: "MENSAL",
    price: 190,
    badge: "Recomendado",
  },
  // ---------- Consultoria ----------
  {
    guideKey: "consultoria-perfil-ia",
    category: "Consultoria",
    name: "Consultoria de Perfil com IA",
    tagline: "Posicionamento para quem está começando",
    features: [
      "Análise completa do perfil feita com inteligência artificial",
      "Diagnóstico de posicionamento: quem você é, para quem fala, o que vende",
      "Manual de posicionamento para seguir no dia a dia",
    ],
    billing: "PONTUAL",
    price: 997,
  },
  // ---------- UGC ----------
  {
    guideKey: "ugc-portfolio-casting",
    category: "UGC",
    name: "Portfólio UGC + Casting",
    tagline: "Agenciado Lumi para sempre",
    features: [
      "Portfólio UGC profissional",
      "Ensaio de fotos ultrarrealistas geradas com IA",
      "Casting e entrada no banco de talentos Lumi",
      "Agenciamento vitalício: a Lumi envia o perfil para marcas e traz propostas",
    ],
    billing: "PONTUAL",
    price: 500,
    cardMode: "FIXED",
    cardPrice: 600,
    maxInstallments: 5,
    terms: "O valor paga a preparação do perfil; trabalhos com marcas não são garantidos.",
  },
  // ---------- Figuras Públicas ----------
  {
    guideKey: "figuras-publicas-tabela",
    category: "Figuras Públicas",
    name: "Conteúdo para Figuras Públicas",
    tagline: "Qualidade, não quantidade",
    features: ["Edição e produção personalizada", "YouTube, Instagram, TikTok e Facebook", "Postagem e gestão do conteúdo"],
    billing: "MENSAL",
    price: 3500,
    cardMode: "NONE",
    terms: "Pagamento mensal à vista, sem parcelamento.",
  },
  {
    guideKey: "figuras-publicas-oferta-decisao",
    category: "Figuras Públicas",
    name: "Figuras Públicas · Fechamento no ato",
    tagline: "Condição válida apenas no momento da negociação",
    features: ["Mesma entrega da tabela", "R$ 500 de desconto pelo pagamento à vista no ato"],
    billing: "MENSAL",
    price: 3000,
    cardMode: "NONE",
    terms: "Condição especial válida somente no momento da negociação. Pagamento à vista.",
  },
  {
    guideKey: "figuras-publicas-parceria",
    category: "Figuras Públicas",
    name: "Parceria Lumi · Figuras Públicas",
    tagline: "Contrato de 6 meses",
    features: [
      "Mesma entrega da tabela",
      "Mensalidade de R$ 3.000",
      "Participação de 40% na receita gerada pelos conteúdos produzidos pela Lumi",
    ],
    billing: "MENSAL",
    price: 3000,
    cardMode: "NONE",
    minMonths: 6,
    badge: "Parceria",
    terms: "A participação de 40% vale somente para a receita originada dos conteúdos produzidos pela Lumi, conforme definido em contrato.",
  },
  // ---------- Gestão Completa ----------
  {
    guideKey: "gestao-completa",
    category: "Gestão Completa",
    name: "Gestão Completa",
    tagline: "Social media, tráfego e audiovisual",
    features: [
      "Social media: planejamento, calendário, copy e postagem",
      "Audiovisual: captação mensal com câmera",
      "Tráfego pago: criação e gestão de campanhas",
      "Relatório mensal de métricas e resultados",
    ],
    billing: "MENSAL",
    price: 5900,
    priceIsFrom: true,
    minMonths: 6,
    terms: "Verba de anúncios paga à parte pelo cliente. Escopo e valor final definidos após diagnóstico.",
  },
];
